package ungdungnghenhac;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.PrintWriter;
import java.util.Vector;
import java.util.concurrent.TimeUnit;
import javax.sound.sampled.AudioFileFormat;
import javax.sound.sampled.AudioSystem;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javazoom.jl.player.Player;

/**
 *
 * @author Ngô Duy Minh
 */
public class MainForm extends javax.swing.JFrame {

    JFileChooser fileDialog = new JFileChooser();
    String fileName;
    Player player;
    Thread playingThread;
    Thread strackBarThread;
    int max = 0;
    Vector header = new Vector();
    Vector data = new Vector();
    DefaultTableModel tblModel;
    String fileList = "C:\\data\\song.txt";

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        header.add("Tên bài hát");
        header.add("Thời lượng");
        header.add("Vị trí");
        loadSongList();
        tblModel = (DefaultTableModel) tblSongList.getModel();
        tblModel.setDataVector(data, header);
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSelectedFile = new javax.swing.JTextField();
        btnOpen = new javax.swing.JButton();
        SliderProgress = new javax.swing.JSlider();
        btnPlay = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSongList = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniOpen = new javax.swing.JMenuItem();
        mniStart = new javax.swing.JMenuItem();
        mniStop = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btnClose = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniAboutUs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tập tin đang mở");

        btnOpen.setText("Chọn bài");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        btnPlay.setText("Bắt đầu ");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnStop.setText("Kết thúc");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnAdd.setText("Thêm bài hát");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSave.setText("Lưu danh sách");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa khỏi danh sách");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblSongList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSongList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSongListMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblSongListMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblSongList);

        jMenu1.setText("File");

        mniOpen.setText("Chọn bài");
        mniOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOpenActionPerformed(evt);
            }
        });
        jMenu1.add(mniOpen);

        mniStart.setText("Bắt đầu");
        mniStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniStartActionPerformed(evt);
            }
        });
        jMenu1.add(mniStart);

        mniStop.setText("Kết thúc");
        mniStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniStopActionPerformed(evt);
            }
        });
        jMenu1.add(mniStop);
        jMenu1.add(jSeparator1);

        btnClose.setText("Thoát");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jMenu1.add(btnClose);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        mniAboutUs.setText("Thông tin ứng dụng");
        mniAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAboutUsActionPerformed(evt);
            }
        });
        jMenu2.add(mniAboutUs);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSelectedFile)
                        .addGap(18, 18, 18)
                        .addComponent(btnOpen))
                    .addComponent(SliderProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPlay)
                        .addGap(18, 18, 18)
                        .addComponent(btnStop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSelectedFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SliderProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlay)
                    .addComponent(btnStop)
                    .addComponent(btnAdd)
                    .addComponent(btnSave)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int getDuration(File f) throws Exception {
        int mili = 0;
        int sec = 0;
        AudioFileFormat fileFormat = AudioSystem.getAudioFileFormat(f);
        long microsecond = (long) fileFormat.properties().get("duration");
        mili = (int) (microsecond / 100);
        sec = mili / 1000;
        return sec;
    }

    private String getDurationFormat(File file) throws Exception {
        AudioFileFormat fileFormat = AudioSystem.getAudioFileFormat(file);
        long microsecond = (long) fileFormat.properties().get("duration");
        long sec = TimeUnit.MICROSECONDS.toSeconds(microsecond);
        long minute = TimeUnit.MICROSECONDS.toMinutes(microsecond);
        long hour = TimeUnit.MICROSECONDS.toHours(microsecond);
        return hour + ":" + minute + ":" + ":" + sec;
    }

    private void mniStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniStopActionPerformed
        btnStopActionPerformed(null);
    }//GEN-LAST:event_mniStopActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        try {
            int result = fileDialog.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File f = fileDialog.getSelectedFile();
                if (f.isFile()) {
                    this.txtSelectedFile.setText(f.getCanonicalPath());
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        fileName = txtSelectedFile.getText();
        FileInputStream fis = null;
        BufferedInputStream bis = null;
        File f = new File(fileName);
        try {
            fis = new FileInputStream(f);
            bis = new BufferedInputStream(fis);
            player = new Player(bis);
            max = getDuration(f);
            SliderProgress.setMaximum(max);
        } catch (Exception e) {
        }
        playingThread = new Thread() {
            public void run() {
                try {
                    player.play();
                } catch (Exception e) {
                }
            }
        };
        strackBarThread = new Thread() {
            public void run() {
                try {
                    int n = 0;
                    while (!player.isComplete() && playingThread.isAlive()) {
                        SliderProgress.setValue(n++);
                        Thread.sleep(1000);
                    }
                    SliderProgress.setValue(max);
                } catch (Exception e) {
                }
                btnStopActionPerformed(null);
            }
        };
        playingThread.start();
        strackBarThread.start();
        btnPlay.setEnabled(false);
        btnStop.setEnabled(true);
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        if (player != null) {
            player.close();
        }
        btnPlay.setEnabled(true);
        btnStop.setEnabled(false);
        SliderProgress.setValue(0);
        playingThread.interrupt();
        strackBarThread.interrupt();

    }//GEN-LAST:event_btnStopActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        formWindowClosing(null);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void mniOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniOpenActionPerformed
        btnOpenActionPerformed(null);
    }//GEN-LAST:event_mniOpenActionPerformed

    void addFilesToTable(File[] files) throws Exception {
        for (File song : files) {
            String duration = getDurationFormat(song);
            String name = song.getName();
            String location = song.getCanonicalPath();
            Vector v = new Vector();
            v.add(name);
            v.add(duration);
            v.add(location);
            data.add(v);
        }
        tblSongList.updateUI();
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        fileDialog.setMultiSelectionEnabled(true);
        int result = fileDialog.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File[] files = fileDialog.getSelectedFiles();
            try {
                addFilesToTable(files);
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblSongListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSongListMouseClicked
        int row = tblSongList.getSelectedRow();
        String location = tblSongList.getValueAt(row, 2).toString();
        txtSelectedFile.setText(location);
        if (evt.getClickCount() == 2) {
            if (playingThread != null) {
                btnStopActionPerformed(null);
            }
            btnPlayActionPerformed(null);
        }
    }//GEN-LAST:event_tblSongListMouseClicked

    private void tblSongListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSongListMouseReleased
        if (tblSongList.isEditing()) {
            int row = tblSongList.getSelectedRow();
            int column = tblSongList.getSelectedColumnCount();
            tblSongList.getCellEditor(row, column).cancelCellEditing();
            tblModel.fireTableDataChanged();
        }
    }//GEN-LAST:event_tblSongListMouseReleased

        void loadSongList() {
            try {
                FileReader fr = new FileReader(fileList);
                BufferedReader br = new BufferedReader(fr);
                String song;
                while ((song = br.readLine()) != null)  {
                    String info [ ] = song.split(",");
                    String name = info[0];
                    String duration = info[1];
                    String location = info[2];
                    Vector row = new Vector();
                    row.add(name);
                    row.add(duration);
                    row.add(location);
                    data.add(row);
                }
                br.close();
                fr.close();
            } catch (Exception e) {
            }
        }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            File f = new File(fileList);
            PrintWriter pw = new PrintWriter(f);
            int n = data.size();
            for (int i = 0; i < n; i++) {
                Vector row = (Vector) data.get(i);
                String s = row.get(0) + "," + row.get(1) + "," + row.get(2);
                pw.println(s);
            }
            pw.close();
            JOptionPane.showMessageDialog(this, "Bài hát đã được lưu vào danh sách");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int pos = tblSongList.getSelectedRow();
        if (pos >=0)    {
            int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không", "Xác nhận", 
                    JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION);
            data.remove(pos);
            tblSongList.updateUI();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int result = JOptionPane.showConfirmDialog(this, "Bạn có muốn đóng chương trình không ?",
                "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION)   {
            System.exit(0);
        }   else {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void mniStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniStartActionPerformed
        btnPlayActionPerformed(null);
    }//GEN-LAST:event_mniStartActionPerformed

    private void mniAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAboutUsActionPerformed
        AboutUsDialog aboutDialog = new AboutUsDialog(this, true);
        aboutDialog.setLocationRelativeTo(null);
        aboutDialog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_mniAboutUsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider SliderProgress;
    private javax.swing.JButton btnAdd;
    private javax.swing.JMenuItem btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mniAboutUs;
    private javax.swing.JMenuItem mniOpen;
    private javax.swing.JMenuItem mniStart;
    private javax.swing.JMenuItem mniStop;
    private javax.swing.JTable tblSongList;
    private javax.swing.JTextField txtSelectedFile;
    // End of variables declaration//GEN-END:variables
}
